% Script generated by Brainstorm (12-Sep-2022)

% Input files
sFiles = [];
SubjectNames = {...
    '162935'};
RawFiles = {...
    'E:\files\data\162935\162935_MEG_Restin_preproc\162935\MEG\Restin\rmegpreproc\162935_MEG_3-Restin_rmegpreproc.mat'};

% Start a new report
bst_report('Start', sFiles);

% Process: Create link to raw file
sFiles = bst_process('CallProcess', 'process_import_data_raw', sFiles, [], ...
    'subjectname',    SubjectNames{1}, ...
    'datafile',       {RawFiles{1}, 'FT-TIMELOCK'}, ...
    'channelreplace', 1, ...
    'channelalign',   1, ...
    'evtmode',        'value');

% Save and display report
ReportFile = bst_report('Save', sFiles);
bst_report('Open', ReportFile);
% bst_report('Export', ReportFile, ExportDir);
% bst_report('Email', ReportFile, username, to, subject, isFullReport);

