% Script generated by Brainstorm (04-Oct-2022)

% iterate files
fid = fopen('n_files.txt');
while true
  thisline = fgetl(fid);
  if ~ischar(thisline); break; end  %end of file
    %now check whether the string in thisline is a "word", and store it if it is.
    %then
    disp('===== Working on file =====');
    disp(thisline);
    path_pattern = 'E:\\files\\data\\%s\\%s_MEG_Restin_preproc\\%s\\MEG\\Restin\\rmegpreproc\\%s_MEG_%d-Restin_rmegpreproc.mat';
    for i=3:5
        path = sprintf(path_pattern, thisline, thisline, thisline, thisline, i);
        disp(path);
        % Input files
        sFiles = [];
        SubjectNames = {...
            thisline};
        RawFiles = {...
           path};

        % Start a new report
        bst_report('Start', sFiles);

        % Process: Import MEG/EEG: Existing epochs
        sFiles = bst_process('CallProcess', 'process_import_data_epoch', sFiles, [], ...
            'subjectname',   SubjectNames{1}, ...
            'condition',     '', ...
            'datafile',      {{RawFiles{1}}, 'FT-TIMELOCK'}, ...
            'iepochs',       [], ...
            'eventtypes',    '', ...
            'createcond',    0, ...
            'channelalign',  1, ...
            'usectfcomp',    1, ...
            'usessp',        1, ...
            'freq',          [], ...
            'baseline',      [], ...
            'blsensortypes', 'MEG, EEG');

        % Save and display report
        ReportFile = bst_report('Save', sFiles);
        %bst_report('Open', ReportFile);
        % bst_report('Export', ReportFile, ExportDir);
        % bst_report('Email', ReportFile, username, to, subject, isFullReport);

    end
  end
  fclose(fid);

